### ISSUE TITLE
https://github.com/Maratyszcza/pthreadpool.git

### ISSUE THREAD

**Issue by kck2025** [Maratyszcza/pthreadpool#7]
Detected root directory: /home/pi/NNPACK-darknet
/usr/local/lib/python2.7/dist-packages/confu/manifest.py:36: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  manifest_yaml = yaml.load(manifest_text)
Configuring dependency pthreadpool
Configuring dependency fxdiv
Configuring dependency googletest
Configuring dependency googlebenchmark
Traceback (most recent call last):
  File "./configure.py", line 396, in <module>
    main(sys.argv[1:]).generate()
  File "./configure.py", line 36, in main
    (build.deps.pthreadpool, build.deps.fxdiv, build.deps.fp16): any,
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/deps.py", line 48, in __getattr__
    config = configure.main(["--target", self._target])
  File "/home/pi/NNPACK-darknet/deps/pthreadpool/configure.py", line 20, in main
    build.static_library("pthreadpool", [build.cc(src) for src in sources])
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/unix.py", line 72, in cc
    return self._compile("cc", source_path)
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/unix.py", line 56, in _compile
    source_path = validate_source_path(source_path, self.source_dir)
  File "/usr/local/lib/python2.7/dist-packages/confu/validators.py", line 67, in validate_source_path
    .format(source_path=source_path))
ValueError: Specified source file /home/pi/NNPACK-darknet/deps/pthreadpool/src/threadpool-legacy.c does not exist

**Comment by kck2025** [comment]
this issue was not relative to the version of python. I have figured out the reason, because the author of the project ptheadpool was refactoring those code and rename all of files, but forgetting to update the config.py file in new version. I try to revert the repo in a specified version then re-compile the whole project then the issue was solved.
